name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "0 2 * * *"
  workflow_dispatch: 

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          ACCLAIM_USER: "mohamed-ctrl878"
